# -*- coding: utf-8 -*-
"""NLPProject_LibrarySentiment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ykxkeAeZfCOJ38ikaAwSvK0nCUIw-c1k
"""

import nltk
import tensorflow as tf
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

path_to_file = tf.keras.utils.get_file('hamlet.txt', 'https://www.gutenberg.org/cache/epub/1524/pg1524.txt')

play = open(path_to_file, 'rb').read() #the entire corpus is now accessible via the variable named 'text'
play = play.decode(encoding='utf-8')
print ('Total number of characters in the corpus is:', len(play)) # returns 178981 total characters
print('The first 500 characters of the corpus are as follows:\n', play[:1000])

from textblob import TextBlob

blob = TextBlob(play)
print('sentiment of the sonnet is:', blob.sentiment)

if blob.sentiment.polarity < 0:
  print("negative sentiment")
else:
  print("positive sentiment")

if blob.sentiment.subjectivity < 0.5:
  print("objective")
else:
  print("subjective")
  
#blob.words